### ISSUE TITLE
Validation: Implement validation of the exchange deposit crypto step for the CCXT adapter

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mate#10]
**Description**

To enable and ensure smooth crypto deposits through the CCXT adapter, we need a solid validation process for the "exchange deposit crypto" step configuration. Before any deposit action is executed, this validation logic should review the configuration to ensure it matches expected standards, which will prevent any potential deposit errors. A typical configuration is below:

```
steps:
   - type: "exchange_deposit_crypto"
     adapter: "ccxt"
     config:
        exchange: "binance"
        currency: "USDC"
        amount: 123.45
        destination_address: "0x123456"
```

**Acceptance Criteria**

- [ ] The validation logic should check for the presence and validity of all mandatory fields (e.g., exchange, currency, amount, source_address).
- [ ] The validation process should identify and flag any inconsistencies or unsupported configurations.
- [ ] Proper error messages should be returned to guide users in case of configuration issues.
- [ ] Unit tests should be in place to ensure the validation logic catches typical mistakes and edge cases.
