### ISSUE TITLE
Validation: Implement validation of exchange swap step for the CCXT adapter

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mate#13]
**Description**
To avoid any errors during the execution of the `Exchange.Swap` step, we need to add validation of the configuration for the step. The validation should ensure the necessary details required for an exchange swap, such as from asset, amounts and slippage, are provided and accurate. 

A typical configuration for this step may look as follows:
```
steps:
   - type: Exchange.Swap
        adapter: ccxt
        config:
          exchange: binance
          from: USD
          to: BUSD
          maxSlippageBPS: 20
          amount: 1000
```
The configuration should be updated to include all information required for the execution of an exchange swap.

**Acceptance Criteria**

- [x] The validation logic checks and verifies each parameter in the `Exchange.Swap` step config.
- [x] For any missing or incorrect configuration details, appropriate errors are thrown.
- [x] Unit tests are in place to confirm that the validation process identifies both correct and incorrect configurations.
