### ISSUE TITLE
Validation: Implement validation of the chain transfer step for the evm chain adapter

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mate#14]
**Description**

In order to prevent errors during the execution of the Chain.Transfer step for EVM-based chains, we need a validation mechanism in place. This validation will ensure that the configuration details for a chain transfer, such as the sender, receiver, amount, gas fee, and other essential parameters, are provided correctly.

A representative configuration for this step might resemble:

```yaml
steps:
  - type: Chain.Transfer
    adapter: @mate/adapter-evm-chain
    config:
      chain_id: 4220
      from_address: 0xSenderAddress
      to_address: 0xReceiverAddress
      amount: 2.5
      gasFee: 21000
      gasPrice: 20gwei
```

The configuration should encompass all essential information needed to execute a transfer on an EVM-based chain.

**Acceptance Criteria:**

- [ ] The validation logic thoroughly inspects and validates each parameter in the `Chain.Transfer` step config.
- [ ] Whenever there are missing or incorrect configuration details, errors are thrown.
- [ ] Unit and integration tests are created to confirm the validation mechanism works for both valid and invalid configurations.
