### ISSUE TITLE
Validation: Implement validation of the bridge swap step for the squid adapter

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mate#15]
**Description**

To prevent errors in the execution of the `Bridge.Swap` step using the squid-adapter, we need to add some validaion. This validation will confirm that all necessary configuration parameters for a bridge swap, such as origin chain, destination chain, tokens involved, amounts, fees, and any other relevant details, are appropriately provided and are valid.

A typical configuration for this step might look like:
```
steps:
  - type: Bridge.Swap
    adapter: squid-adapter
    config:
      originChain_id: 1
      destinationChain_id: 4220
      fromTokenAddress: 0x123456
      toTokenAddress: 0x123456
      amount: 500
      minAmountOut: 495
      fee: 0.5%
```
This configuration should include all the necessary information to facilitate a token swap between chains using the squid adapter.

**Acceptance Criteria**

- [x] The validation logic checks and verifies each parameter within the Bridge.Swap step configuration.
- [x] For instances where configuration details are either missing or mismatched the expected criteria, errors are thrown.
- [x] Unit and integration tests are implemented to ensure that the validation correctly identifies both valid and invalid configurations.
