### ISSUE TITLE
Validation: Implement validation of the chain swap step for the evm chain adapter

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mate#16]
**Description**

To reduce the likelihood of errors during the chain.swap step, we need to add validation of the configuration. The validation should verify that all the necessary parameters for executing the chain.swap step, including from token, to token, amount, gas fees, and other details are provided and valid.

A typical configuration for this step may look like this:
``` yaml
steps:
  - type: Chain.Swap
    adapter: evm-chain-adapter
    config:
      dex: mento
      chain_id: 4220
      fromToken: ETH
      toToken: mETH
      amount: 2
     minAmount: 1.99
```
The configuration should include all the details needed to perform a swap using a DEX on a specified chain.

**Acceptance Criteria**

- [ ] The validation mechanism checks and verifies each parameter provided in the chain.swap step configuration
- [ ] Error messages are generated when configuration values are not present, invalid, or do not match the expected formats
- [ ] Unit tests are added that validate the implemented checks can identify invalid and valid configurations accurately
