### ISSUE TITLE
Validation: Implement logic to validate the squid adapter configuration

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mate#25]
**Description**

To prevent failures due to incorrect configuration we should add logic that verifies the squid adapter configuration is valid. The squid configuration can be seen in the adapter configuration section below:

Review [adapter-ccxt.AdpterConfigValidator](https://github.com/mento-protocol/mate/blob/main/packages/adapter-ccxt/src/validation/AdapterConfigValidator.ts) for an example.

```
adapters:
   - id: ccxt
     adapter: "@mate/adapter-ccxt"
     config:
        exchanges:
           - id: binance
             apiKey: "TestKey"
             apiSecret: "TestSecret"
   - id: squid
     adapter: "@mate/adapter-squid"
     config:
        integratorId: mate-sdk
        baseUrl: https://api.0xsquid.com
```

**Acceptance Criteria**
- [x] Class is created that Implements [IValidator](https://github.com/mento-protocol/mate/blob/main/packages/sdk/src/interfaces/IValidator.ts)
- [x] Logic verifies configuration id is correct and config includes integrator id + baseURL
- [x] Unit tests are added to ensure validator works as expected
