### ISSUE TITLE
Validation: Implement validation of adapter configuration for the CCXT adapter

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mate#7]
**Description**

To ensure smooth and error-free operations, it's essential that the CCXT adapter configuration is validated. The validation process is intended to catch any inconsistencies, omissions, or errors that could disrupt normal functioning. At app startup the `init()` function of the adapter will be called. At this point, the validation logic should be executed to ensure the adapter-specific config is valid. The adapter config will look like this:

```
adapters:
   - id: ccxt
     adapter: "@mate/adapter-ccxt"
     config:
        exchanges:
           - id: binance
             api_key: "TestKey"
             api_secret: "TestSecret"
```
**Acceptance Criteria**
- [x] Init function validates config and throws errors for any failures
- [x] Unit tests are added to verify validation works as expected
