### ISSUE TITLE
Validation: Implement validation of exchange withdraw crypto step config for the CCXT adapter

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mate#8]
**Description**
To maintain the integrity of operations and avoid any errors during crypto withdrawals, it's essential that the configuration for the "exchange withdraw crypto" step is validated for the CCXT adapter. This validation is intended to ensure the necessary details required for withdrawals, like destination addresses, amounts, and relevant fees, are provided and accurate. A typical configuration for this step might look as follows:
```
steps:
   - id: withdraw_crypto
     type: "exchange_withdraw_crypto"
     adapter: "ccxt"
     config:
        exchange: "binance"
        currency: "BTC"
        amount: 0.01
        address: "0x..."
        chain: "1"
        fee: 0.0005
```
The config should be updated to include int information needed to facilitate the exchange.

**Acceptance Criteria**

- [x] The validation logic accurately checks and verifies each parameter in the "exchange withdraw crypto" step.
- [x] For any missing or incorrect configuration details, appropriate errors are thrown.
- [x] Unit tests are in place to confirm that the validation process identifies both correct and incorrect configurations.
